version: '3'

services:
  frontend:
    build: 
      context: frontend/
    container_name: junto-frontend
    volumes:
      - ./frontend/:/src
    ports:
      - "3000:3000"
    command:
      "npm run dev"
    depends_on:
      - api
  api:
    build:
      context: api/
    container_name: junto-api
    volumes:
      - ./api/:/app
    environment:
      # Variables to connect to our Postgres server
      PGUSER: postgres
      PGPASSWORD: postgres
      PGDATABASE: api_dev
      PGPORT: 5432
      PGHOST: db
    ports:
      - "4000:4000"
    depends_on:
      - db
  db:
    image: postgres:9.6
    container_name: junto-db
    environment:
      # Set user/password for Postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      # Set a path where Postgres should store the data
      PGDATA: /var/lib/postgresql/data/pgdata
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
# Define the volumes
volumes:
  pgdata: