name: API

on: [push]

env:
  CI: true
  MIX_ENV: test

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:9.6-alpine
        env:
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.10.2
          otp-version: 22.2
      - name: Install Dependencies
        run: |
          cd api
          mix deps.get
      - name: Run Tests
        run: |
          cd api
          mix test
