name: Code Quality

on: [pull_request]

env:
  CI: true
  MIX_ENV: test

jobs:
  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup elixir
        uses: actions/setup-elixir@v1
        with:
          elixir-version: 1.10.3
          otp-version: 22.2
      - name: Download reviewdog
        run: |
          wget -q https://github.com/reviewdog/reviewdog/releases/download/v0.10.2/reviewdog_0.10.2_Linux_x86_64.tar.gz
          tar xzf reviewdog_0.10.2_Linux_x86_64.tar.gz
      - name: Install Dependencies
        run: |
          mix deps.get
      - name: Check Format
        run: |
          mix format --check-formatted
      - name: Credo check
        run: |
          export REVIEWDOG_GITHUB_API_TOKEN=${{ secrets.github_token }}
          mix credo suggest --strict --format=flycheck \
          | ./reviewdog -efm="%f:%l:%c: %t: %m" -efm="%f:%l: %t: %m" -name="credo" -reporter="github-pr-review" -level="error"
